<?php

namespace BYRWEB\app001\clientCard;




use BYRWEB\app001\card\Card;
use BYRWEB\app001\card\CardRecord;
use BYRWEB\base\ADbObject;
use BYRWEB\base\Exception;
use BYRWEB\base\IDbObject;


class ClientCard extends ADbObject
{
	/**
	 *
	 */
	public
	function __construct()
	{
		parent::__construct();
		$this->setRecordObject(new ClientCardRecord());
	}
	
	
	
	/**
	 * @param $id
	 *
	 * @return ClientCardRecord
	 * @throws \BYRWEB\base\exceptions\Exception
	 */
	public
	function get($id)
	{
		/**
		 * @var $record ClientCardRecord
		 */
		$record           = parent::get($id);
		$record->password = null;
		
		return $record;
	}
	
	
	
	/**
	 * @param      $data
	 *
	 * @param bool $updateOnDuplicate
	 *
	 * @return bool|ClientCardRecord
	 * @throws \Exception
	 */
	public
	function add($data, $updateOnDuplicate = false)
	{
		$clientCard = parent::add($data, $updateOnDuplicate);
		
		
		if (!$clientCard) {
			return false;
		}
		$card = new Card();
		$card->setDb($this->db);
		$cardRecord         = $card->get($data->card_id);
		$cardRecord->in_use = 1;
		$cardRecord->update();
		
		return $clientCard;
	}
	
	
	
	/**
	 * @param $data
	 *
	 * @return bool|ClientCardRecord
	 */
	public
	function update($data)
	{
		return parent::update($data);
	}
	
	
	
	/**
	 * @param null  $filter
	 * @param null  $keyword
	 * @param null  $limit
	 * @param array $order
	 * @param null  $selectOnly
	 *
	 * @return ClientCard[]
	 * @throws Exception
	 */
	public
	function find($filter = null, $keyword = null, $limit = null, array $order = [], $selectOnly = null, $lookIn = null)
	{
		return parent::find($filter, $keyword, $limit, $order, $selectOnly, $lookIn);
	}
	
	
	
	/**
	 * @return ClientCardRecord
	 */
	public
	function getRecordObject(): ClientCardRecord
	{
		return parent::getRecordObject(); // TODO: Change the autogenerated stub
	}
	
	
}