<?php
/**
 * Created by IntelliJ IDEA.
 * User: unal
 * Date: 29.10.2015
 * Time: 16:20
 */

namespace BYRWEB\app001\cashSale;




use BYRWEB\app900\saleSaleItem\SaleSaleItemRecord;
use BYRWEB\base\ADbObject;
use BYRWEB\base\ADbRecord;
use BYRWEB\base\IDbObject;
use BYRWEB\base\IWidget;
use BYRWEB\base\WTDbUtils;
use BYRWEB\app001\Saleitem;
use BYRWEB\common\Session;


/**
 * Class CashSale
 *
 * @package BYRWEB\app001\cashSale
 * @method CashSaleRecord getRecordObject()
 */
class CashSale extends ADbObject implements IDbObject, IWidget
{
	
	
	public
	function __construct()
	{
		parent::__construct();
		$this->setRecordObject(new CashSaleRecord());
	}
	
	
	
	public static
	function widgetForDashboard()
	{
		
		$sql = file_get_contents(__DIR__ . '/sql/widget/weekly_totals.sql');
		$sth = WTDbUtils::$db->prepare($sql);
		$sth->execute(['enterprise_id' => Session::user()->enterprise_id]);
		$rows                   = $sth->fetchAll(\PDO::FETCH_ASSOC);
		$stats['weekly_totals'] = $rows;
		
		///
		
		$sql = file_get_contents(__DIR__ . '/sql/widget/stats_totals.sql');
		$sth = WTDbUtils::$db->prepare($sql);
		$sth->execute(['enterprise_id' => Session::user()->enterprise_id]);
		$rows                  = $sth->fetch(\PDO::FETCH_ASSOC);
		$stats['stats_totals'] = $rows;
		
		return $stats;
	}
	
	
	
	public static
	function getTotalSales($client_id)
	{
		$sql = 'SELECT sum(grand) as grand FROM ' . CashSaleRecord::TABLE_NAME . " where client_id=$client_id";
		$sth = WTDbUtils::$db->query($sql);
		ADbRecord::evalError($sth);
		
		$row = $sth->fetch(\PDO::FETCH_ASSOC);
		if (!$row) {
			return 0;
		}
		
		return $row['grand'] * 1.0;
	}
	
	
	
//	public static
//	function updateStats($client_id)
//	{
//
//		$sql = 'SELECT sum(grand) as grand FROM ' . CashSaleRecord::TABLE_NAME . " where client_id=$client_id";
//		$sth = WTDbUtils::$db->query($sql);
//		ADbRecord::evalError($sth);
//
//		$row = $sth->fetch(\PDO::FETCH_ASSOC);
//		if (!$row) {
//			return;
//		}
//
//		$total_sales = $row['grand'];
//
//		$loop = null;
//
//		do {
//			$sql         = "UPDATE `app999.client_stats`
//            SET total_sales=$total_sales
//            WHERE client_id=$client_id";
//			$num_of_rows = WTDbUtils::$db->execUpdate($sql);
//
//			if ($num_of_rows === 0) {
//				$sql = WTDbUtils::getInsertQuery('`app999.client_stats`', ['client_id'], [$client_id]);
//				WTDbUtils::$db->execForce($sql);
//				$loop = true;
//			}
//			else {
//				$loop = false;
//			}
//		} while ($loop);
//	}
	
	
	
	//	public
	//	function add1($data, $updateOnDuplicate = false)
	//	{
	//		/**
	//		 * @var $saleRecord CashSaleRecord
	//		 */
	//		$saleRecord = parent::add($data, $updateOnDuplicate); // TODO: Change the autogenerated stub
	//
	//		//        foreach ($this->sale_items as $saleItemRecord) {
	//		//            $saleItemRecord->sale_id = $saleRecord->sale_id;
	//		//            $saleItemRecord->add();
	//		//        }
	//
	//		return $saleRecord;
	//	}
	//
	//
	//
	//	public
	//	function add2()
	//	{
	//
	//		$this->db->beginTransaction();
	//
	//		$sql = WTDbUtils::getInsertQuery('sale', get_object_vars($this));
	//		$this->db->execInsert($sql, 'sale');
	//		$this->sale_id = $this->db->lastInsertId();
	//
	//		/**
	//		 * @var $saleItem \BYRWEB\app001\saleSaleItem\SaleSaleItem
	//		 */
	//		foreach ($this->sale_items as $saleItem) {
	//			$saleItem->sale_id = $this->sale_id;
	//			$saleItem->add();
	//		}
	//
	//		$this->db->commit();
	//
	//		return $this->sale_id;
	//	}
	//
	
	
	//	/**
	//	 * @return CashSaleRecord
	//	 */
	//	public
	//	function getRecordObject()
	//	{
	//		return parent::getRecordObject(); // TODO: Change the autogenerated stub
	//	}
	
	
}