<?php
/**
 * Created by IntelliJ IDEA.
 * User: unal
 * Date: 29.10.2015
 * Time: 16:20
 */

namespace BYRWEB\app001\cashSale;

use BYRWEB\app001\saleSaleItem\SaleSaleItemRecord;
use BYRWEB\base\ADbObject;
use BYRWEB\base\IDbObject;
use BYRWEB\base\IWidget;
use BYRWEB\base\WTDbUtils;
use BYRWEB\app001\Saleitem;
use BYRWEB\common\Session;


class CashSale extends ADbObject implements IDbObject, IWidget
{


    public function __construct()
    {
        $this->setRecordObject(new CashSaleRecord());
    }

    public static function widgetForDashboard()
    {
        $db  = WTDbUtils::$db;

        ///

        $sql = file_get_contents(__DIR__ . '/sql/widget/weekly_totals.sql');
        $sth = $db->prepare($sql);
        $sth->execute(['enterprise_id' => Session::user()->enterprise_id]);
        $rows = $sth->fetchAll(\PDO::FETCH_ASSOC);
        $stats['weekly_totals'] = $rows;

        ///

        $sql = file_get_contents(__DIR__ . '/sql/widget/stats_totals.sql');
        $sth = $db->prepare($sql);
        $sth->execute(['enterprise_id' => Session::user()->enterprise_id]);
        $rows = $sth->fetch(\PDO::FETCH_ASSOC);
        $stats['stats_totals'] = $rows;

        return $stats;
    }

    public static function updateStats($client_id)
    {
        $db = WTDbUtils::$db;

        $sql         = "SELECT sum(grand) as grand FROM sale where client_id=$client_id";
        $sth         = $db->query($sql);
        $row         = $sth->fetch(\PDO::FETCH_ASSOC);
        $total_sales = $row['grand'];

        $sql = "UPDATE client_stats
            SET total_sales=$total_sales
            WHERE client_id=$client_id";
        $db->execUpdate($sql);
    }

    public function add1($data, $updateOnDuplicate = false)
    {
        /**
         * @var $saleRecord CashSaleRecord
         */
        $saleRecord = parent::add($data, $updateOnDuplicate); // TODO: Change the autogenerated stub

//        foreach ($this->sale_items as $saleItemRecord) {
//            $saleItemRecord->sale_id = $saleRecord->sale_id;
//            $saleItemRecord->add();
//        }

        return $saleRecord;
    }

    public function add2()
    {

        $this->db->beginTransaction();

        $sql = WTDbUtils::getInsertQuery('sale', get_object_vars($this));
        $this->db->execInsert($sql, 'sale');
        $this->sale_id = $this->db->lastInsertId();

        /**
         * @var $saleItem \BYRWEB\app001\saleSaleItem\SaleSaleItem
         */
        foreach ($this->sale_items as $saleItem) {
            $saleItem->sale_id = $this->sale_id;
            $saleItem->add();
        }

        $this->db->commit();

        return $this->sale_id;
    }


    /**
     * @return CashSaleRecord
     */
    public function getRecordObject()
    {
        return parent::getRecordObject(); // TODO: Change the autogenerated stub
    }


}