<?php
/**
 * Created by IntelliJ IDEA.
 * User: unal
 * Date: 21.01.2016
 * Time: 11:28
 */


namespace BYRWEB\app001\couponSubject;




use BYRWEB\base\ADbObject;


class CouponSubject extends ADbObject
{
	/**
	 *
	 */
	public
	function __construct()
	{
		parent::__construct();
		$this->setRecordObject(new CouponSubjectRecord());
	}
	
	//    /**
	//     * @param $id
	//     *
	//     * @return CouponSubjectRecord
	//     */
	//    public function get($id)
	//    {
	//        return parent::get($id);
	//    }
	//
	//    /**
	//     * @param      $data
	//     *
	//     * @param bool $updateOnDuplicate
	//     *
	//     * @return bool|\BYRWEB\app001\couponSubject\CouponSubjectRecord
	//     */
	//    public function add(array $data, $updateOnDuplicate = false):bool
	//    {
	//        if (array_key_exists('saleitem_id', $data)) {
	//            unset($data['saleitem_group_id']);
	//            if (array_key_exists('brand_id', $data)) {
	//                unset($data['brand_id']);
	//            }
	//        }
	//
	//        return parent::add($data, $updateOnDuplicate);
	//    }
	//
	//    /**
	//     * @param $data
	//     *
	//     * @return bool|CouponSubjectRecord
	//     */
	//    public function update($data)
	//    {
	//        return parent::update($data);
	//    }
	//
	//    /**
	//     * @param null  $filter
	//     * @param null  $keyword
	//     * @param null  $limit
	//     * @param array $order
	//     * @param null  $selectOnly
	//     *
	//     * @return CouponSubjectRecord[]
	//     * @throws \BYRWEB\base\Exception
	//     */
	//    public function find($filter = null, $keyword = null, $limit = null, array $order = [], $selectOnly = null, $lookIn = null)
	//    {
	//        return parent::find($filter, $keyword, $limit, $order, $selectOnly, $lookIn); // TODO: Change the autogenerated stub
	//    }
	
	
}