<?php

namespace BYRWEB\app001\clientGroup;


use BYRWEB\base\ADbObject;
use BYRWEB\base\Exception;
use BYRWEB\base\IDbObject;

class ClientGroup extends ADbObject implements IDbObject
{
    /**
     *
     */
    public function __construct()
    {
        $this->setRecordObject(new ClientGroupRecord());
    }

    /**
     * @param $id
     *
     * @return ClientGroupRecord
     */
    public function get($id)
    {
        /**
         * @var $record ClientGroupRecord
         */
        $record           = parent::get($id);
        $record->password = null;

        return $record;
    }

    /**
     * @param $data
     *
     * @return bool|ClientGroupRecord
     */
    public function add($data, $updateOnDuplicate = false)
    {
        return parent::add($data, $updateOnDuplicate);
    }

    /**
     * @param $data
     *
     * @return bool|ClientGroupRecord
     */
    public function update($data)
    {
        /**
         * @var $rows ClientGroupRecord
         */
        $rows = parent::find(['client_id' => $data['client_id']]);
        /**
         * @var $clientGroupRecord ClientGroupRecord
         */
        $clientGroupRecord = $rows[0];
        $clientGroupRecord->setDb($this->db);
        $clientGroupRecord->client_group_id = $data['client_group_id'];
        $clientGroupRecord->is_primary      = 1;
        $clientGroupRecord->update();

        if (!$clientGroupRecord) {
            return false;
        }

        return true;

    }

    /**
     * @param null  $filter
     * @param null  $keyword
     * @param null  $limit
     * @param array $order
     * @param null  $selectOnly
     *
     * @throws Exception
     */
    public function find($filter = null, $keyword = null, $limit = null, array $order = [], $selectOnly = null, $lookIn = null)
    {
        return parent::find($filter, $keyword, $limit, $order, $selectOnly, $lookIn);
    }


    /**
     * @return ClientGroupRecord
     */
    public function getRecordObject()
    {
        return parent::getRecordObject(); // TODO: Change the autogenerated stub
    }


}