<?php
/**
 * Created by IntelliJ IDEA.
 * User: unal
 * Date: 30.10.2015
 * Time: 13:01
 */

namespace BYRWEB\app001\saleSaleItem;

use BYRWEB\base\ADbObject;
use BYRWEB\base\WTDbUtils;
use BYRWEB\nexus\PriceManager;


class SaleSaleItem extends ADbObject
{

    public function __construct()
    {
        $this->setRecordObject(new SaleSaleItemRecord());
    }

    /**
     * @param null       $filter
     * @param null       $keyword
     * @param null       $limit
     * @param array|null $order
     * @param null       $selectOnly
     *
     * @return SaleSaleItemRecord|SaleSaleItemRecord[]
     */
    public function find($filter = null, $keyword = null, $limit = null, array $order = [], $selectOnly = null, $lookIn = null)
    {
        return parent::find($filter, $keyword, $limit, $order, $selectOnly, $lookIn); // TODO: Change the autogenerated stub
    }


}